import { accounts, navigation } from '../data/demo'

function Icon({ children }) { return <span className="icon" aria-hidden="true">{children}</span> }
function Avatar({ children }) { return <span className="avatar dark">{children}</span> }

export default function AppShell({ user, role, active, setActive, status, notify, onLogout, toast, children }) {
  const groups = navigation[role] || navigation.Admin
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">S</span><span>Skill<span>Pulse</span><small>AI</small></span></div><div className="demo-pill"><span className="live-dot" /> {status === 'postgresql' ? 'PostgreSQL connected' : 'Demo workspace'}</div><nav>{groups.map(([label, items]) => <div className="nav-group" key={label}><p>{label}</p>{items.map(([item, icon]) => <button className={active === item ? 'nav-item active' : 'nav-item'} key={item} onClick={() => setActive(item)}><Icon>{icon}</Icon>{item}{item.toLowerCase().includes('follow') && <b>4</b>}</button>)}</div>)}</nav><div className="sidebar-footer"><div className="privacy"><Icon>◉</Icon><span><strong>Privacy first</strong><small>Consent-based tracking</small></span></div><button className="profile-mini" onClick={() => notify('Profile settings opened')}><Avatar>{user.initials}</Avatar><span><strong>{user.name}</strong><small>{role} account</small></span><span>⌄</span></button><button className="logout-button" onClick={onLogout}>Sign out</button></div></aside><main className="main-content"><header className="topbar"><div className="crumb"><span>{role} workspace</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><label className="role-select"><span>Viewing as</span><select value={role} onChange={(event) => { const next = accounts.find((account) => account.role === event.target.value); if (next) notify(`Use ${next.email} to sign in as ${next.role}`) }}>{accounts.map((account) => <option key={account.role}>{account.role}</option>)}</select></label><button className="icon-button" aria-label="Notifications" onClick={() => notify('You have 4 follow-ups needing attention')}>♧<i /></button><Avatar>{user.initials}</Avatar></div></header><div className="content-wrap">{children}<footer className="app-footer"><span><i className="live-dot" /> All systems operational</span><span>Last data sync: 8 min ago</span><span className="footer-right">IVR integration <strong>Coming soon / disabled</strong></span></footer></div></main>{toast && <div className="toast"><span>✓</span>{toast}</div>}</div>
}
