import { courses, trainees } from '../data/demo'
import { apiFetch } from '../api'

function Table({ headers, rows }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${index}-${row[0]}`}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div> }
function Heading({ eyebrow, title, subtitle, action, notify }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><button className="button primary" onClick={() => { apiFetch('/api/actions', { method: 'POST', headers: { 'Content-Type': 'application/json', 'x-skillpulse-role': localStorage.getItem('skillpulse-role') || 'Trainee' }, body: JSON.stringify({ action }) }).catch(() => null); notify(`${action} opened`) }}>{action} ↗</button></section> }
function SharedPage({ active, notify, role }) {
  if (role === 'Employer' && active === 'Candidates') return <><Heading eyebrow="EMPLOYER TALENT PIPELINE" title="Candidates" subtitle="Review matched trainees and move the right people into your hiring process." action="Request candidates" notify={notify} /><section className="panel section-panel"><Table headers={['CANDIDATE', 'SKILL MATCH', 'LOCATION', 'NEXT STEP']} rows={['Aarav Mehta|92%|Pune|Review profile', 'Riya Nair|88%|Kochi|Schedule interview', 'Sana Khan|81%|Jaipur|Request assessment'].map((row) => row.split('|'))} /></section></>
  if (role === 'Employer' && active === 'Employment verification') return <><Heading eyebrow="EMPLOYER VERIFICATION" title="Employment verification" subtitle="Confirm role, start date, wage, and retention for associated trainees." action="Confirm selected" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Awaiting confirmation" value="18" detail="Candidate records" /><Metric label="Verified this month" value="42" detail="Employer confirmed" color="blue" /><Metric label="Retention signal" value="91%" detail="After 90 days" color="orange" /><Metric label="Feedback due" value="6" detail="Help close the loop" color="red" /></div></section></>
  if (role === 'Employer' && active === 'Feedback') return <><Heading eyebrow="EMPLOYER FEEDBACK" title="Feedback" subtitle="Share practical signals that help providers improve job readiness." action="Submit feedback" notify={notify} /><section className="panel section-panel"><div className="gap-list">{['Technical readiness', 'Workplace communication', 'Role-specific confidence'].map((item) => <div className="gap-row" key={item}><span className="gap-icon">⌁</span><div><strong>{item}</strong><small>Feedback requested for the latest cohort</small></div><button onClick={() => notify(`${item} feedback opened`)}>Rate →</button></div>)}</div></section></>
  if (role === 'Admin' && active === 'Initiatives') return <><Heading eyebrow="PROGRAMME CONNECTORS" title="Initiatives" subtitle="Monitor external skilling programmes and synchronize mapped records." action="Sync Initiative Alpha" notify={notify} /><section className="panel section-panel"><div className="initiative-list">{['Initiative Alpha', 'Initiative Beta', 'Initiative Gamma'].map((name, index) => <div className="initiative-row" key={name}><span className="initiative-icon">⇄</span><div><strong>{name}</strong><small>Mock API · {128 - index * 17} records · Last sync 8 min ago</small></div><span className="badge teal">Connected</span><button onClick={() => notify(`${name} sync requested`)}>Sync ↗</button></div>)}</div></section></>
  if (role === 'Admin' && active === 'Audit logs') return <><Heading eyebrow="GOVERNANCE" title="Audit logs" subtitle="Review every data change, verification, and integration action." action="Export audit log" notify={notify} /><section className="panel section-panel"><Table headers={['USER', 'ACTION', 'RECORD', 'TIME', 'SOURCE']} rows={[['Arjun Kapoor', 'Initiative sync', 'INIT-1', 'Today 10:42', 'System'], ['Meera Shah', 'Outcome verified', 'SP-0007', 'Today 09:18', 'Provider'], ['Rohan Verma', 'Employment confirmed', 'SP-0001', 'Yesterday 16:25', 'Employer']]} /></section></>
  if (role === 'Admin' && active === 'Skill gaps') return <><Heading eyebrow="PLATFORM INTELLIGENCE" title="Skill gaps" subtitle="Identify the capabilities most often missing between training and work." action="Create recommendation" notify={notify} /><section className="panel section-panel"><div className="gap-list">{[['Power BI', '38% of Junior Data Analyst matches'], ['Advanced diagnostics', '27% of EV Technician matches'], ['Git workflows', '19% of Web Developer matches']].map(([skill, detail]) => <div className="gap-row" key={skill}><span className="gap-icon">⌁</span><div><strong>{skill}</strong><small>{detail}</small></div><button onClick={() => notify(`${skill} recommendation opened`)}>Recommend →</button></div>)}</div></section></>
  if (role === 'Admin' && active === 'Analytics') return <><Heading eyebrow="PLATFORM ANALYTICS" title="Analytics" subtitle="Compare transparent outcome metrics across providers, courses, and districts." action="Download report" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Placement rate" value="62%" detail="+8.4% this period" /><Metric label="Employment rate" value="54%" detail="1,750 currently working" color="orange" /><Metric label="180-day retention" value="43%" detail="+6.7% this period" color="blue" /><Metric label="Top missing skill" value="Power BI" detail="38% of matches" color="red" /></div></section></>
  if (active === 'Trainees') return <><Heading eyebrow="PEOPLE DIRECTORY" title="Trainees" subtitle="Track participation, progress, and outcomes across the learner network." action="Add trainee" notify={notify} /><section className="panel section-panel"><Table headers={['TRAINEE', 'COURSE', 'DISTRICT', 'STATUS', 'CONSENT']} rows={trainees.map((item) => [<strong key={`${item.name}-name`}>{item.name}</strong>, item.course, item.district, <span className="badge teal" key={`${item.name}-status`}>{item.status}</span>, <span className="badge teal" key={`${item.name}-consent`}>Given</span>])} /></section></>
  if (active === 'Courses') return <><Heading eyebrow="PROGRAMME CATALOGUE" title="Courses" subtitle="Compare course delivery and measurable employment outcomes." action="Add course" notify={notify} /><section className="panel section-panel"><Table headers={['COURSE', 'PROVIDER', 'DURATION', 'COMPLETION', 'PLACEMENT']} rows={courses.map((course) => [<strong key={`${course[0]}-name`}>{course[0]}</strong>, course[1], course[2], <span className="badge blue" key={`${course[0]}-completion`}>{course[3]}</span>, <span className="badge teal" key={`${course[0]}-placement`}>{course[4]}</span>])} /></section></>
  if (active === 'My courses') return <><Heading eyebrow="MY LEARNING" title="My courses" subtitle="Your enrolled learning and assessment progress." action="Open course" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Current course" value="82%" detail="Web Development Fundamentals" /><Metric label="Skills acquired" value="4" detail="HTML, CSS, JavaScript, Git" color="blue" /><Metric label="Assessment" value="Passed" detail="Certification ready" color="orange" /></div></section></>
  if (active === 'My skills') return <><Heading eyebrow="SKILL PROFILE" title="My skills" subtitle="Skills you have acquired and recommended next steps." action="Find recommended course" notify={notify} /><section className="panel section-panel"><div className="gap-list">{['HTML and semantic structure', 'CSS layout and responsive design', 'JavaScript fundamentals', 'Git and collaboration'].map((skill) => <div className="gap-row" key={skill}><span className="gap-icon">✓</span><div><strong>{skill}</strong><small>Acquired · Web Development Fundamentals</small></div><span className="badge teal">Verified</span></div>)}</div></section></>
  if (active === 'My employment' || active === 'Employment verification') return <><Heading eyebrow="EMPLOYMENT RECORD" title={active} subtitle="Keep employment details current and outcome confidence high." action="Update record" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Status" value="Employed" detail="Verified by employer" /><Metric label="Role" value="Junior Developer" detail="Northstar Digital" color="blue" /><Metric label="Monthly wage" value="₹32,000" detail="Last verified 18 Sep" color="orange" /></div></section></>
  if (active === 'My follow-ups' || active === 'Follow-ups') return <><Heading eyebrow="FEEDBACK LOOP" title="Follow-ups" subtitle="Keep every 30, 90, and 180-day checkpoint moving." action="Run follow-up" notify={notify} /><section className="panel section-panel"><Table headers={['TRAINEE', 'CHECKPOINT', 'DUE', 'CHANNEL', 'STATUS']} rows={['Sana Khan|90-day|Today|WhatsApp|Due', 'Riya Nair|30-day|Tomorrow|SMS|Sent', 'Vikram Kumar|180-day|24 Oct|Email|Responded'].map((row) => row.split('|'))} /></section></>
  if (active === 'Outcome timeline') return <><Heading eyebrow="MY OUTCOME TIMELINE" title="Outcome timeline" subtitle="Your journey from enrolment to lasting employment." action="Download timeline" notify={notify} /><section className="panel section-panel"><div className="journey">{['Enrolled · 15 Jan 2026', 'Training completed · 08 Apr 2026', 'Certified · 20 Apr 2026', 'Placed · 02 May 2026', 'Employed · 10 May 2026', '30-day follow-up · Verified'].map((stage, index) => <div className="journey-step" key={stage}><div className={`step-marker marker-${index % 5}`}>{index + 1}</div><div className="step-copy"><span>{stage}</span><strong>Verified</strong><div className="bar"><i style={{ width: '100%' }} /></div></div><small>Done</small></div>)}</div></section></>
  const provider = role === 'Provider'
  const title = active === 'Skill gaps' ? (provider ? 'Cohort skill gaps' : 'Skill gaps') : active === 'Analytics' ? (provider ? 'Provider analytics' : 'Analytics') : active === 'Feedback' ? 'Employer feedback' : 'Outcome review'
  const subtitle = provider ? 'Measure your cohorts, placement outcomes, and readiness gaps.' : 'Transparent metrics and clear next actions for your role.'
  return <><Heading eyebrow={provider ? 'PROVIDER INSIGHTS' : 'SKILLPULSE INSIGHTS'} title={title} subtitle={subtitle} action={provider ? 'Review cohort report' : 'Export report'} notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label={provider ? 'Your completion rate' : 'Placement rate'} value={provider ? '78%' : '62%'} detail={provider ? 'Across 12 cohorts' : '+8.4% this period'} /><Metric label={provider ? 'Your placement rate' : 'Employment rate'} value={provider ? '62%' : '54%'} detail={provider ? 'Across 3 courses' : '1,750 currently working'} color="orange" /><Metric label={provider ? 'Average wage' : 'Retention'} value={provider ? '₹28,400' : '43%'} detail={provider ? 'Monthly starting wage' : 'After 180 days'} color="blue" /><Metric label={provider ? 'Attendance risk' : 'Confidence'} value={provider ? '12' : '82/100'} detail={provider ? 'Records need review' : 'Prototype indicator'} color="red" /></div></section></>
}
function Metric({ label, value, detail, color = 'teal' }) { return <article className={`metric-card ${color}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
export default function RolePage({ role, active, notify }) { return <div className={`role-page ${role.toLowerCase()}`}><SharedPage active={active} notify={notify} role={role} /></div> }
