import { courses, trainees } from '../data/demo'

function Table({ headers, rows }) { return <div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${index}-${row[0]}`}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div> }
function Heading({ eyebrow, title, subtitle, action, notify }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><button className="button primary" onClick={() => notify(`${action} opened`)}>{action} ↗</button></section> }
function SharedPage({ active, notify }) {
  if (active === 'Trainees') return <><Heading eyebrow="PEOPLE DIRECTORY" title="Trainees" subtitle="Track participation, progress, and outcomes across the learner network." action="Add trainee" notify={notify} /><section className="panel section-panel"><Table headers={['TRAINEE', 'COURSE', 'DISTRICT', 'STATUS', 'CONSENT']} rows={trainees.map((item) => [<strong key={`${item.name}-name`}>{item.name}</strong>, item.course, item.district, <span className="badge teal" key={`${item.name}-status`}>{item.status}</span>, <span className="badge teal" key={`${item.name}-consent`}>Given</span>])} /></section></>
  if (active === 'Courses') return <><Heading eyebrow="PROGRAMME CATALOGUE" title="Courses" subtitle="Compare course delivery and measurable employment outcomes." action="Add course" notify={notify} /><section className="panel section-panel"><Table headers={['COURSE', 'PROVIDER', 'DURATION', 'COMPLETION', 'PLACEMENT']} rows={courses.map((course) => [<strong key={`${course[0]}-name`}>{course[0]}</strong>, course[1], course[2], <span className="badge blue" key={`${course[0]}-completion`}>{course[3]}</span>, <span className="badge teal" key={`${course[0]}-placement`}>{course[4]}</span>])} /></section></>
  if (active === 'My courses') return <><Heading eyebrow="MY LEARNING" title="My courses" subtitle="Your enrolled learning and assessment progress." action="Open course" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Current course" value="82%" detail="Web Development Fundamentals" /><Metric label="Skills acquired" value="4" detail="HTML, CSS, JavaScript, Git" color="blue" /><Metric label="Assessment" value="Passed" detail="Certification ready" color="orange" /></div></section></>
  if (active === 'My skills') return <><Heading eyebrow="SKILL PROFILE" title="My skills" subtitle="Skills you have acquired and recommended next steps." action="Find recommended course" notify={notify} /><section className="panel section-panel"><div className="gap-list">{['HTML and semantic structure', 'CSS layout and responsive design', 'JavaScript fundamentals', 'Git and collaboration'].map((skill) => <div className="gap-row" key={skill}><span className="gap-icon">✓</span><div><strong>{skill}</strong><small>Acquired · Web Development Fundamentals</small></div><span className="badge teal">Verified</span></div>)}</div></section></>
  if (active === 'My employment' || active === 'Employment verification') return <><Heading eyebrow="EMPLOYMENT RECORD" title={active} subtitle="Keep employment details current and outcome confidence high." action="Update record" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Status" value="Employed" detail="Verified by employer" /><Metric label="Role" value="Junior Developer" detail="Northstar Digital" color="blue" /><Metric label="Monthly wage" value="₹32,000" detail="Last verified 18 Sep" color="orange" /></div></section></>
  if (active === 'My follow-ups' || active === 'Follow-ups') return <><Heading eyebrow="FEEDBACK LOOP" title="Follow-ups" subtitle="Keep every 30, 90, and 180-day checkpoint moving." action="Run follow-up" notify={notify} /><section className="panel section-panel"><Table headers={['TRAINEE', 'CHECKPOINT', 'DUE', 'CHANNEL', 'STATUS']} rows={['Sana Khan|90-day|Today|WhatsApp|Due', 'Riya Nair|30-day|Tomorrow|SMS|Sent', 'Vikram Kumar|180-day|24 Oct|Email|Responded'].map((row) => row.split('|'))} /></section></>
  if (active === 'Outcome timeline') return <><Heading eyebrow="MY OUTCOME TIMELINE" title="Outcome timeline" subtitle="Your journey from enrolment to lasting employment." action="Download timeline" notify={notify} /><section className="panel section-panel"><div className="journey">{['Enrolled · 15 Jan 2026', 'Training completed · 08 Apr 2026', 'Certified · 20 Apr 2026', 'Placed · 02 May 2026', 'Employed · 10 May 2026', '30-day follow-up · Verified'].map((stage, index) => <div className="journey-step" key={stage}><div className={`step-marker marker-${index % 5}`}>{index + 1}</div><div className="step-copy"><span>{stage}</span><strong>Verified</strong><div className="bar"><i style={{ width: '100%' }} /></div></div><small>Done</small></div>)}</div></section></>
  const title = active === 'Skill gaps' ? 'Skill gaps' : active === 'Analytics' ? 'Analytics' : active === 'Initiatives' ? 'Initiatives' : active === 'Audit logs' ? 'Audit logs' : active === 'Feedback' ? 'Employer feedback' : 'Outcome review'
  return <><Heading eyebrow="SKILLPULSE INSIGHTS" title={title} subtitle="Transparent metrics and clear next actions for your role." action="Export report" notify={notify} /><section className="panel section-panel"><div className="mini-grid"><Metric label="Placement rate" value="62%" detail="+8.4% this period" /><Metric label="Employment rate" value="54%" detail="1,750 currently working" color="orange" /><Metric label="Retention" value="43%" detail="After 180 days" color="blue" /><Metric label="Confidence" value="82/100" detail="Prototype indicator" color="red" /></div></section></>
}
function Metric({ label, value, detail, color = 'teal' }) { return <article className={`metric-card ${color}`}><p>{label}</p><strong>{value}</strong><small>{detail}</small></article> }
export default function RolePage({ role, active, notify }) { return <div className={`role-page ${role.toLowerCase()}`}><SharedPage active={active} notify={notify} /></div> }
